export const OFFER_LIST = 'Offers';
export const MY_OFFERS = 'My offers';
export const OFFER_DETAIL = 'Offer detail';
export const CREATE_OFFER = 'Create new offer';
export const FILTER = 'Filter';
export const LOGIN = 'Login';
export const REGISTER = 'Register';
export const HOME_NAVIGATOR = 'Home';
export const AUTH_NAVIGATOR = 'Auth';
