# Generated by Django 3.2.2 on 2021-05-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Name of the product')),
                ('shop', models.CharField(max_length=100, verbose_name='Name of the shop')),
                ('city', models.CharField(max_length=100, verbose_name='City of the shop')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price (€)')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=offers.models.path_and_rename)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'product'],
                'unique_together': {('product', 'shop', 'city', 'date')},
            },
        ),
    ]
