# Generated by Django 3.2.2 on 2021-05-25 08:06

from django.db import migrations, models
import gdstorage.storage
import offers.models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=offers.models.path_and_rename),
        ),
    ]
