# Generated by Django 3.2.2 on 2021-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='User'),
        ),
    ]
