// AUTH
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';

// OFFERS
export const GET_OFFERS_LOADING = 'GET_OFFERS_LOADING';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_FAIL = 'GET_OFFERS_FAIL';
export const CLEAR_OFFERS_STATE = 'CLEAR_OFFERS_STATE';
export const FILTER_OFFERS = 'FILTER_OFFERS';
export const CLEAR_FILTER = 'CLEAR_FILTER'

